#cloud-config
groups:
  - ubuntu: [root,sys]
  #- hashicorp
  # - docker: [sudo]

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: ubuntu
    gecos: ubuntu
    shell: /bin/bash
    primary_group: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,docker
package_update: true
package_upgrade: true
packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-compose
  - openjdk-17-jdk
  - git
runcmd:
  - sudo apt update -y
  - sudo apt-get update -y
  - sudo apt upgrade -y
  - sudo apt-get upgrade -y
  - sudo apt-get install -y ruby-full
  - sudo apt-get install -y build-essential libssl-dev zlib1g-dev
  - sudo gem install fastlane
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - fastlane --version  
  - sudo usermod -aG docker ubuntu
